### ISSUE TITLE
[Q] How to get mutable references to multiple children with identical names?

### ISSUE THREAD

**Issue by Gremious** [eminence/xmltree-rs#24]
My appologies if the answer is obvious, but I have had no luck in getting this to work and did not find help in the docs, so I thought I'd ask directly.

In an xml like this one:

```xml
<foo>
	<bar baz="qux1" quux="corge"/>
	<bar baz="qux2"/>
	<bar baz="qux3"/>
	<bar baz="qux4" quux="corge"/>
</foo>
```

Is it possible to iterate through all `bar` children and remove the `baz` attribute? 

`get_mut_child()` e.g.

```rust
let mut element = Element::parse("file.xml".as_bytes()).unwrap();
let ele: &mut xmltree::Element = element.get_mut_child("bar").unwrap()
ele.attributes.remove("baz");
```

Only gets the first one, and I don't think there exists a `get_mut_children()`.

On the other hand, something like `element.children[n].as_element().unwrap()` ony gives you immutable references that are behind a `&`, and I don't believe there is a `as_mut_element()` or so? I cannot seem to find a way to get the second+ bar child mutably.

**Comment by eminence** [comment]
Hi

It's true that the `get_mut_child` method doesn't help you here, neither does the `as_element()` helper on the `XMLNode` type.  But you can get a mutable reference to the 3rd element by doing something like this:

```rust
let mut elem = Element::parse(data.as_bytes()).unwrap();

// get the 3rd element
if let Some(XMLNode::Element(child)) = elem.children.get_mut(2) {
    child.attributes.remove("baz");
}
```

Does that help?

**Comment by Gremious** [comment]
Ahh, I haven't considered that, that works perfectly fine, thank you very much!

**Comment by eminence** [comment]
Great!
