### ISSUE TITLE
Code changes merged but no new versions published?

### ISSUE THREAD

**Issue by charlietango558** [eminence/xmltree-rs#50]
Curious if this is just a dead project at this point or what the current state is?

We have a use case that would benefit from the changes made in this completed PR https://github.com/eminence/xmltree-rs/pull/37

But no version of this package has actually been published since that fix went in (or for a number of completed PRs).

**Comment by eminence** [comment]
The project is kinda idle, but not exactly dead :)    

I rely on feedback like this to bump up releases on my TODO, so I appreciate that you opened an issue here.  I'll plan on releasing a few version in the next few days

**Comment by charlietango558** [comment]
> The project is kinda idle, but not exactly dead :)
> 
> I rely on feedback like this to bump up releases on my TODO, so I appreciate that you opened an issue here. I'll plan on releasing a few version in the next few days

Thanks so much for the prompt response! Appreciate it

**Comment by eminence** [comment]
v0.11.0 has been released!
